### ISSUE TITLE
当最后一页不是5题时，进度条不会显示完成

### ISSUE THREAD

**Issue by jxlpzqc** [eleflea/mathe-front#1]
https://github.com/eleflea/mathe-front/blob/feca8d2b73a6938156176d52d848f823637f2bb2/src/views/Page.vue#L128

**Comment by eleflea** [comment]
@jxlpzqc 感谢反馈，这个问题已经解决了。

**Comment by jxlpzqc** [comment]
感谢维护，这个网站真的很好用。
